import React, { useState } from 'react';
import { VendorInvoice, VendorProfile } from '../../types';
import {
  FileText,
  X,
  Printer,
  CheckCircle2,
  Clock,
  CreditCard,
  Building2,
  Download,
  ShieldCheck,
  DollarSign,
  Smartphone,
  Send,
  Sparkles
} from 'lucide-react';

interface InvoiceModalProps {
  isOpen: boolean;
  onClose: () => void;
  invoice: VendorInvoice | null;
  vendor: VendorProfile | null;
  onPayInvoice: (invoiceId: string, paymentMethod: 'credit_card' | 'mobile_money' | 'bank_transfer' | 'cash') => Promise<void>;
}

export const InvoiceModal: React.FC<InvoiceModalProps> = ({
  isOpen,
  onClose,
  invoice,
  vendor,
  onPayInvoice
}) => {
  const [showPayStep, setShowPayStep] = useState(false);
  const [selectedMethod, setSelectedMethod] = useState<'credit_card' | 'mobile_money' | 'bank_transfer'>('credit_card');
  const [isProcessing, setIsProcessing] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);

  // Form states for simulated payment
  const [cardNumber, setCardNumber] = useState('4242 •••• •••• 4242');
  const [mobileNumber, setMobileNumber] = useState(vendor?.phone || '+1 555-0192');

  if (!isOpen || !invoice) return null;

  const currency = invoice.currency || '$';
  const isPaid = invoice.status === 'paid';

  const handlePrint = () => {
    window.print();
  };

  const handleConfirmPayment = async () => {
    setIsProcessing(true);
    try {
      await onPayInvoice(invoice.id, selectedMethod);
      setIsProcessing(false);
      setPaymentSuccess(true);
      setTimeout(() => {
        setPaymentSuccess(false);
        setShowPayStep(false);
      }, 2000);
    } catch (e) {
      setIsProcessing(false);
      alert('Payment processing failed. Please try again.');
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white border border-slate-200 rounded-3xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col my-auto max-h-[92vh]">
        
        {/* Modal Header Bar */}
        <div className="bg-[#1F242D] text-white p-4 sm:p-5 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-[#FF6B00]/20 border border-[#FF6B00]/40 rounded-xl text-[#FF6B00]">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-black text-base text-white">{invoice.invoiceNumber}</h3>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider ${
                  isPaid 
                    ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40' 
                    : 'bg-amber-500/20 text-amber-400 border border-amber-500/40 animate-pulse'
                }`}>
                  {isPaid ? 'Paid & Active' : 'Unpaid - Due'}
                </span>
                {invoice.is7DayAutoGenerated && (
                  <span className="text-[10px] font-bold bg-[#FF6B00]/20 text-[#FF6B00] px-2 py-0.5 rounded-full border border-[#FF6B00]/30 hidden sm:inline">
                    7-Day Auto Renewal Invoice
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-400 font-medium">
                Issue Date: {new Date(invoice.issueDate).toLocaleDateString()} • Due: {new Date(invoice.dueDate).toLocaleDateString()}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 text-xs font-bold"
              title="Print / Save PDF"
            >
              <Printer className="w-4 h-4 text-[#FF6B00]" />
              <span className="hidden sm:inline">Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white rounded-xl transition-all cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Invoice Printable Body Container */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-slate-800 font-sans print:p-0 print:overflow-visible">
          
          {/* Header Branding & Issuer Info */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-slate-200">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <div className="w-8 h-8 bg-[#FF6B00] rounded-lg flex items-center justify-center text-white font-black text-sm">
                  iT
                </div>
                <span className="text-xl font-black text-slate-900 tracking-tight">
                  iTred <span className="text-[#FF6B00]">POS Platform</span>
                </span>
              </div>
              <p className="text-xs text-slate-500">Official Billing & Retail Services Division</p>
              <p className="text-xs text-slate-500">Tax ID: VAT-98231-4012 • billing@itredpos.com</p>
            </div>

            <div className="sm:text-right space-y-1">
              <h2 className="text-2xl font-black text-slate-900 tracking-wider">OFFICIAL INVOICE</h2>
              <p className="text-xs font-mono font-bold text-[#FF6B00]">{invoice.invoiceNumber}</p>
              <p className="text-xs text-slate-500">Date Issued: {new Date(invoice.issueDate).toLocaleDateString()}</p>
              <p className="text-xs font-bold text-slate-700">Payment Due: {new Date(invoice.dueDate).toLocaleDateString()}</p>
            </div>
          </div>

          {/* Billed To Vendor Profile */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-50 p-4 rounded-2xl border border-slate-200 text-xs">
            <div>
              <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-1">BILLED TO VENDOR:</span>
              <p className="text-sm font-bold text-slate-900">{vendor?.businessName || 'Valued Retail Store'}</p>
              <p className="text-slate-600">{vendor?.address || 'Main Commercial District'}</p>
              <p className="text-slate-600">Phone: {vendor?.phone || 'N/A'}</p>
              <p className="text-slate-600">Email: {vendor?.email}</p>
              {vendor?.vatNumber && <p className="text-slate-600 font-mono">VAT Reg: {vendor.vatNumber}</p>}
            </div>

            <div className="sm:text-right border-t sm:border-t-0 sm:border-l border-slate-200 pt-3 sm:pt-0 sm:pl-4">
              <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-1">SUBSCRIPTION PERIOD:</span>
              <p className="font-bold text-slate-900">
                {new Date(invoice.periodStart).toLocaleDateString()} — {new Date(invoice.periodEnd).toLocaleDateString()}
              </p>
              <p className="text-slate-600 mt-1">Status: <strong className={isPaid ? 'text-emerald-600' : 'text-amber-600'}>{invoice.status.toUpperCase()}</strong></p>
              {invoice.paidAt && (
                <p className="text-emerald-600 font-medium mt-0.5">Paid on: {new Date(invoice.paidAt).toLocaleString()}</p>
              )}
            </div>
          </div>

          {/* Itemized Services & Plan Table */}
          <div className="border border-slate-200 rounded-2xl overflow-hidden shadow-xs">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#1F242D] text-white text-[10px] uppercase font-bold tracking-wider">
                <tr>
                  <th className="p-3">Description</th>
                  <th className="p-3">Category</th>
                  <th className="p-3 text-right">Unit Price</th>
                  <th className="p-3 text-center">Qty</th>
                  <th className="p-3 text-right">Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-medium text-slate-700">
                {invoice.items.map(item => (
                  <tr key={item.id} className="hover:bg-slate-50">
                    <td className="p-3 font-bold text-slate-900">{item.description}</td>
                    <td className="p-3">
                      <span className="px-2 py-0.5 bg-slate-100 text-slate-700 rounded text-[10px] font-bold capitalize">
                        {item.category.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="p-3 text-right font-mono">{currency}{item.unitPrice.toFixed(2)}</td>
                    <td className="p-3 text-center font-bold">{item.quantity}</td>
                    <td className="p-3 text-right font-mono font-black text-slate-900">{currency}{item.amount.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Invoice Summary Totals */}
          <div className="flex flex-col sm:flex-row justify-between items-start gap-4 pt-2">
            <div className="text-xs text-slate-500 space-y-1 max-w-sm">
              {invoice.notes && (
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-amber-900">
                  <p className="font-bold text-[11px] mb-0.5">Notice & Payment Terms:</p>
                  <p className="text-[11px]">{invoice.notes}</p>
                </div>
              )}
              <p className="text-[10px] text-slate-400">
                * Invoices generated 7 days prior to plan expiration must be cleared before the expiry date to ensure uninterrupted POS register operation.
              </p>
            </div>

            <div className="w-full sm:w-64 bg-slate-50 p-4 rounded-2xl border border-slate-200 space-y-2 text-xs">
              <div className="flex justify-between text-slate-600">
                <span>Subtotal</span>
                <span className="font-bold font-mono text-slate-900">{currency}{invoice.subtotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>Sales Tax / VAT ({invoice.taxRate}%)</span>
                <span className="font-bold font-mono text-slate-900">{currency}{invoice.taxAmount.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-sm font-black text-slate-900 pt-2 border-t border-slate-200">
                <span>Total Amount Due</span>
                <span className="text-[#FF6B00] font-mono">{currency}{invoice.totalAmount.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {/* Payment Action Section */}
          {!isPaid && !showPayStep && (
            <div className="p-4 bg-orange-50 border border-orange-200 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-[#FF6B00] text-white rounded-xl">
                  <Clock className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-black text-xs text-slate-900">Immediate Payment Available</h4>
                  <p className="text-[11px] text-slate-600">Pay now via Card, Mobile Money, or Bank Transfer to clear invoice instantly.</p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => setShowPayStep(true)}
                className="w-full sm:w-auto px-6 py-3 bg-[#FF6B00] hover:bg-[#e66000] text-white font-black rounded-xl text-xs flex items-center justify-center gap-2 shadow-lg transition-all cursor-pointer active:scale-95"
              >
                <CreditCard className="w-4 h-4" />
                <span>Pay {currency}{invoice.totalAmount.toFixed(2)} Now</span>
              </button>
            </div>
          )}

          {/* Interactive Payment Checkout Panel */}
          {showPayStep && !isPaid && (
            <div className="p-5 bg-slate-900 text-white rounded-2xl border border-slate-800 space-y-4">
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="w-5 h-5 text-emerald-400" />
                  <h4 className="font-black text-sm text-white">Secure Express Payment Gateway</h4>
                </div>
                <button
                  type="button"
                  onClick={() => setShowPayStep(false)}
                  className="text-xs text-slate-400 hover:text-white underline cursor-pointer"
                >
                  Cancel
                </button>
              </div>

              {paymentSuccess ? (
                <div className="py-8 text-center text-emerald-400 space-y-2">
                  <CheckCircle2 className="w-12 h-12 mx-auto animate-bounce text-emerald-400" />
                  <h4 className="text-base font-black text-white">Payment Received Successfully!</h4>
                  <p className="text-xs text-slate-300">Your subscription has been renewed and invoice cleared.</p>
                </div>
              ) : (
                <>
                  {/* Payment Method Selector */}
                  <div className="grid grid-cols-3 gap-2">
                    <button
                      type="button"
                      onClick={() => setSelectedMethod('credit_card')}
                      className={`p-3 rounded-xl border text-xs font-bold flex flex-col items-center gap-1.5 transition-all cursor-pointer ${
                        selectedMethod === 'credit_card'
                          ? 'bg-[#FF6B00] text-white border-[#FF6B00]'
                          : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                      }`}
                    >
                      <CreditCard className="w-4 h-4" />
                      <span>Card Payment</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => setSelectedMethod('mobile_money')}
                      className={`p-3 rounded-xl border text-xs font-bold flex flex-col items-center gap-1.5 transition-all cursor-pointer ${
                        selectedMethod === 'mobile_money'
                          ? 'bg-[#FF6B00] text-white border-[#FF6B00]'
                          : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                      }`}
                    >
                      <Smartphone className="w-4 h-4" />
                      <span>Mobile Money</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => setSelectedMethod('bank_transfer')}
                      className={`p-3 rounded-xl border text-xs font-bold flex flex-col items-center gap-1.5 transition-all cursor-pointer ${
                        selectedMethod === 'bank_transfer'
                          ? 'bg-[#FF6B00] text-white border-[#FF6B00]'
                          : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                      }`}
                    >
                      <Building2 className="w-4 h-4" />
                      <span>Bank Wire</span>
                    </button>
                  </div>

                  {/* Method Inputs */}
                  {selectedMethod === 'credit_card' && (
                    <div className="space-y-2">
                      <label className="text-[11px] font-medium text-slate-300 block">Card Details (Simulated)</label>
                      <input
                        type="text"
                        value={cardNumber}
                        onChange={e => setCardNumber(e.target.value)}
                        className="w-full p-2.5 bg-slate-800 border border-slate-700 rounded-xl text-xs font-mono text-white focus:outline-none focus:ring-2 focus:ring-[#FF6B00]"
                      />
                    </div>
                  )}

                  {selectedMethod === 'mobile_money' && (
                    <div className="space-y-2">
                      <label className="text-[11px] font-medium text-slate-300 block">Mobile Money Phone Number</label>
                      <input
                        type="text"
                        value={mobileNumber}
                        onChange={e => setMobileNumber(e.target.value)}
                        className="w-full p-2.5 bg-slate-800 border border-slate-700 rounded-xl text-xs font-mono text-white focus:outline-none focus:ring-2 focus:ring-[#FF6B00]"
                      />
                    </div>
                  )}

                  {selectedMethod === 'bank_transfer' && (
                    <div className="p-3 bg-slate-800 border border-slate-700 rounded-xl text-xs text-slate-300 space-y-1">
                      <p className="font-bold text-white">Bank Remittance Instructions:</p>
                      <p>Bank: Commerce International Bank</p>
                      <p>Account Name: iTred POS Operations</p>
                      <p>Account No: 8004-9122-4411-90</p>
                      <p>Ref Code: <strong className="text-[#FF6B00] font-mono">{invoice.invoiceNumber}</strong></p>
                    </div>
                  )}

                  <button
                    type="button"
                    disabled={isProcessing}
                    onClick={handleConfirmPayment}
                    className="w-full py-3.5 bg-emerald-500 hover:bg-emerald-600 text-white font-black rounded-xl text-xs sm:text-sm flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg active:scale-95 disabled:opacity-50"
                  >
                    {isProcessing ? (
                      <span>Processing Gateway Transaction...</span>
                    ) : (
                      <>
                        <Send className="w-4 h-4" />
                        <span>Confirm & Authorize Payment ({currency}{invoice.totalAmount.toFixed(2)})</span>
                      </>
                    )}
                  </button>
                </>
              )}
            </div>
          )}

        </div>

        {/* Modal Footer */}
        <div className="bg-slate-50 p-4 border-t border-slate-200 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 bg-slate-200 hover:bg-slate-300 text-slate-800 font-bold rounded-xl text-xs transition-all cursor-pointer"
          >
            Close Invoice Window
          </button>
        </div>

      </div>
    </div>
  );
};
