import React, { useState, useEffect } from 'react';
import {
  VendorProfile,
  Branch,
  BillingPlan,
  BillingServiceAddon,
  VendorSubscription,
  VendorInvoice,
  StaffMember
} from '../../types';
import {
  fetchBillingPlans,
  saveBillingPlan,
  fetchVendorSubscription,
  updateVendorSubscription,
  fetchVendorInvoices,
  createVendorInvoice,
  payVendorInvoice,
  DEFAULT_ORGANIZATION_SERVICES
} from '../../services/db';
import { InvoiceModal } from './InvoiceModal';
import { ConsolePlanModal } from './ConsolePlanModal';
import { getBaseResourceAllowance } from '../../services/resourceEntitlements';
import { ServiceOrderModal } from './ServiceOrderModal';
import {
  CreditCard,
  Calendar,
  Clock,
  Sparkles,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Sliders,
  DollarSign,
  Plus,
  ArrowRight,
  ShieldCheck,
  Building2,
  RefreshCw,
  Printer,
  ChevronRight,
  Wrench,
  BarChart,
  Boxes
} from 'lucide-react';

interface VendorBillingWorkspaceProps {
  vendor: VendorProfile | null;
  activeStaff: StaffMember | null;
  branches: Branch[];
}

export const VendorBillingWorkspace: React.FC<VendorBillingWorkspaceProps> = ({
  vendor,
  activeStaff,
  branches
}) => {
  const [activeTab, setActiveTab] = useState<'subscription' | 'services' | 'invoices' | 'console'>('subscription');
  const [plans, setPlans] = useState<BillingPlan[]>([]);
  const [subscription, setSubscription] = useState<VendorSubscription | null>(null);
  const [invoices, setInvoices] = useState<VendorInvoice[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Modals state
  const [selectedInvoice, setSelectedInvoice] = useState<VendorInvoice | null>(null);
  const [isInvoiceModalOpen, setIsInvoiceModalOpen] = useState(false);

  const [editingConsolePlan, setEditingConsolePlan] = useState<BillingPlan | null>(null);
  const [isConsoleModalOpen, setIsConsoleModalOpen] = useState(false);

  const [selectedServiceForOrder, setSelectedServiceForOrder] = useState<BillingServiceAddon | null>(null);
  const [isServiceOrderModalOpen, setIsServiceOrderModalOpen] = useState(false);

  const vendorId = vendor?.id || 'v_default';

  const loadBillingData = async () => {
    setIsLoading(true);
    try {
      const [fetchedPlans, fetchedSub, fetchedInvs] = await Promise.all([
        fetchBillingPlans(),
        fetchVendorSubscription(vendorId),
        fetchVendorInvoices(vendorId)
      ]);
      setPlans(fetchedPlans);
      setSubscription(fetchedSub);
      setInvoices(fetchedInvs);
    } catch (e) {
      console.warn('Error loading billing data:', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadBillingData();
  }, [vendorId]);

  // Calculate days remaining in subscription
  const daysRemaining = subscription ? Math.ceil(
    (new Date(subscription.expiryDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
  ) : 0;

  const is7DayWindow = daysRemaining <= 7;
  const isExpired = daysRemaining <= 0;

  // Unpaid invoices
  const unpaidInvoices = invoices.filter(i => i.status === 'unpaid_due' || i.status === 'overdue');
  const autoRenewalInvoice = invoices.find(i => i.is7DayAutoGenerated && i.status === 'unpaid_due');

  // Handle Plan Upgrade / Switch
  const handleSelectPlan = async (plan: BillingPlan, periodMonths: number = 1) => {
    if (!subscription) return;
    const confirmSwitch = window.confirm(
      `Switch subscription to "${plan.name}" at $${plan.priceMonthly * periodMonths} for ${periodMonths} Month(s)?`
    );
    if (!confirmSwitch) return;

    try {
      const now = new Date();
      const newExpiry = new Date(now.getTime() + periodMonths * 30 * 24 * 60 * 60 * 1000);

      const updatedSub = await updateVendorSubscription(vendorId, {
        planId: plan.id,
        planName: plan.name,
        priceMonthly: plan.priceMonthly,
        billingPeriodMonths: periodMonths,
        expiryDate: newExpiry.toISOString(),
        status: 'active'
      });

      // Create initial invoice for the new plan if price > 0
      if (plan.priceMonthly > 0) {
        const subtotal = plan.priceMonthly * periodMonths;
        const taxAmount = subtotal * 0.08;
        await createVendorInvoice(vendorId, {
          invoiceNumber: `INV-${now.getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`,
          issueDate: now.toISOString(),
          dueDate: newExpiry.toISOString(),
          periodStart: now.toISOString(),
          periodEnd: newExpiry.toISOString(),
          items: [
            {
              id: `item_${Date.now()}`,
              description: `Plan Upgrade: ${plan.name} (${periodMonths} Month Period)`,
              category: 'plan_renewal',
              unitPrice: plan.priceMonthly,
              quantity: periodMonths,
              amount: subtotal
            }
          ],
          subtotal,
          taxRate: 8,
          taxAmount,
          totalAmount: subtotal + taxAmount,
          currency: '$',
          status: 'unpaid_due',
          is7DayAutoGenerated: false,
          notes: 'Plan switch requested by vendor.'
        });
      }

      await loadBillingData();
      alert(`Successfully switched plan to ${plan.name}!`);
    } catch (e) {
      alert('Error updating plan.');
    }
  };

  // Handle Pay Invoice
  const handlePayInvoice = async (
    invoiceId: string,
    method: 'credit_card' | 'mobile_money' | 'bank_transfer' | 'cash'
  ) => {
    await payVendorInvoice(vendorId, invoiceId, method);
    await loadBillingData();
  };

  // Handle Order Organization Service
  const handleOrderService = async (
    service: BillingServiceAddon,
    targetBranchId: string,
    preferredDate: string,
    notes: string
  ) => {
    const targetBranch = branches.find(b => b.id === targetBranchId);
    const branchName = targetBranch ? targetBranch.name : 'Main Store';
    const now = new Date();
    const subtotal = service.price;
    const taxAmount = subtotal * 0.08;

    const newInv = await createVendorInvoice(vendorId, {
      invoiceNumber: `INV-SRV-${now.getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`,
      issueDate: now.toISOString(),
      dueDate: preferredDate,
      periodStart: now.toISOString(),
      periodEnd: preferredDate,
      items: [
        {
          id: `item_srv_${Date.now()}`,
          description: `Organization Service: ${service.title} (${branchName})`,
          category: service.category === 'stocktake' ? 'stocktake' : service.category === 'consultancy' ? 'consultancy' : 'service_addon',
          unitPrice: service.price,
          quantity: 1,
          amount: subtotal
        }
      ],
      subtotal,
      taxRate: 8,
      taxAmount,
      totalAmount: subtotal + taxAmount,
      currency: '$',
      status: 'unpaid_due',
      is7DayAutoGenerated: false,
      notes: `Service Booking: Preferred Date ${preferredDate} at ${branchName}. ${notes}`
    });

    await loadBillingData();
    setSelectedInvoice(newInv);
    setIsInvoiceModalOpen(true);
  };

  // Handle Console Save Plan
  const handleSaveConsolePlan = async (plan: BillingPlan) => {
    await saveBillingPlan(plan);
    await loadBillingData();
  };

  if (isLoading) {
    return (
      <div className="p-12 text-center space-y-3">
        <RefreshCw className="w-8 h-8 text-[#FF6B00] animate-spin mx-auto" />
        <p className="text-xs font-bold text-slate-600">Loading Billing & Subscription Engine...</p>
      </div>
    );
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-7xl mx-auto font-sans text-slate-800">
      
      {/* Workspace Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-[#1F242D] text-white p-6 rounded-3xl shadow-xl border border-slate-800">
        <div className="flex items-center gap-4">
          <div className="p-3.5 bg-[#FF6B00]/20 border border-[#FF6B00]/40 rounded-2xl text-[#FF6B00]">
            <CreditCard className="w-7 h-7" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl sm:text-2xl font-black text-white tracking-tight">Vendor Billing & Subscriptions</h1>
              <span className="px-2.5 py-0.5 bg-[#FF6B00] text-white font-black rounded-full text-[10px] uppercase tracking-wider">
                Retail Engine
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Control subscription plans, view 7-day advance auto-invoices, and order organization services.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={loadBillingData}
            className="p-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 text-xs font-bold"
            title="Refresh Invoices & Status"
          >
            <RefreshCw className="w-4 h-4 text-[#FF6B00]" />
            <span>Sync Engine</span>
          </button>
        </div>
      </div>

      {/* 7-DAY ADVANCE AUTO-INVOICE CRITICAL BANNER */}
      {is7DayWindow && (
        <div className="p-5 bg-gradient-to-r from-amber-500/10 via-orange-500/10 to-amber-500/10 border-2 border-[#FF6B00]/40 rounded-3xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 shadow-lg animate-pulse">
          <div className="flex items-start gap-3.5">
            <div className="p-2.5 bg-[#FF6B00] text-white rounded-2xl shrink-0 mt-0.5">
              <AlertTriangle className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-black text-sm text-slate-900">7-DAY ADVANCE RENEWAL INVOICE GENERATED</h3>
                <span className="text-[10px] font-mono font-bold bg-[#FF6B00] text-white px-2 py-0.5 rounded-md">
                  {daysRemaining <= 0 ? 'OVERDUE' : `${daysRemaining} DAYS REMAINING`}
                </span>
              </div>
              <p className="text-xs text-slate-700 mt-1 leading-relaxed">
                Your subscription <strong>{subscription?.planName}</strong> expires on <strong>{new Date(subscription?.expiryDate || '').toLocaleDateString()}</strong>. In accordance with system policy, an advance renewal invoice was automatically generated 7 days prior to expiry.
              </p>
            </div>
          </div>

          {autoRenewalInvoice && (
            <button
              onClick={() => {
                setSelectedInvoice(autoRenewalInvoice);
                setIsInvoiceModalOpen(true);
              }}
              className="px-6 py-3 bg-[#FF6B00] hover:bg-[#e66000] text-white font-black rounded-2xl text-xs flex items-center gap-2 shadow-xl transition-all cursor-pointer shrink-0 active:scale-95"
            >
              <FileText className="w-4 h-4" />
              <span>View & Pay Auto Invoice (${autoRenewalInvoice.totalAmount.toFixed(2)})</span>
            </button>
          )}
        </div>
      )}

      {/* Active Subscription Summary Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        
        {/* Current Plan Card */}
        <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block">Current Plan</span>
          <div className="flex items-center justify-between">
            <h3 className="text-base font-black text-slate-900">{subscription?.planName || 'Pro Commerce'}</h3>
            <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded-full text-[10px] font-black uppercase">
              {subscription?.status || 'Active'}
            </span>
          </div>
          <p className="text-xs font-mono font-bold text-[#FF6B00]">
            ${subscription?.priceMonthly} <span className="text-[10px] text-slate-500 font-sans">/ month</span>
          </p>
        </div>

        {/* Plan Expiry Date Card */}
        <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block">Plan Expiry Date</span>
          <div className="flex items-center justify-between">
            <h3 className="text-base font-black text-slate-900">
              {subscription ? new Date(subscription.expiryDate).toLocaleDateString() : 'N/A'}
            </h3>
            <Calendar className="w-5 h-5 text-slate-400" />
          </div>
          <p className={`text-xs font-bold ${is7DayWindow ? 'text-[#FF6B00] font-mono' : 'text-slate-600'}`}>
            {daysRemaining > 0 ? `${daysRemaining} Days Remaining` : 'Expired — Please Renew'}
          </p>
        </div>

        {/* Active Branches Usage */}
        <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block">Store Branch Capacity</span>
          <div className="flex items-center justify-between">
            <h3 className="text-base font-black text-slate-900">
              {branches.length} <span className="text-xs text-slate-400 font-normal">Active Branches</span>
            </h3>
            <Building2 className="w-5 h-5 text-slate-400" />
          </div>
          <p className="text-xs text-slate-500 font-medium">
            Plan Allows Multi-Branch Operating
          </p>
        </div>

        {/* Unpaid Invoices Counter */}
        <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block">Outstanding Invoices</span>
          <div className="flex items-center justify-between">
            <h3 className="text-base font-black text-slate-900">
              {unpaidInvoices.length} <span className="text-xs text-slate-400 font-normal">Due</span>
            </h3>
            <FileText className="w-5 h-5 text-slate-400" />
          </div>
          <p className="text-xs text-slate-500 font-medium">
            Total Due: <strong className="font-mono text-slate-900">${unpaidInvoices.reduce((s, i) => s + i.totalAmount, 0).toFixed(2)}</strong>
          </p>
        </div>

      </div>

      {/* Main Navigation Tabs */}
      <div className="flex border-b border-slate-200 gap-2 overflow-x-auto pb-1">
        <button
          onClick={() => setActiveTab('subscription')}
          className={`px-5 py-3 rounded-2xl font-black text-xs transition-all cursor-pointer flex items-center gap-2 whitespace-nowrap ${
            activeTab === 'subscription'
              ? 'bg-[#1F242D] text-white shadow-md'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <CreditCard className="w-4 h-4 text-[#FF6B00]" />
          <span>Subscription Plans & Expiry</span>
        </button>

        <button
          onClick={() => setActiveTab('services')}
          className={`px-5 py-3 rounded-2xl font-black text-xs transition-all cursor-pointer flex items-center gap-2 whitespace-nowrap ${
            activeTab === 'services'
              ? 'bg-[#1F242D] text-white shadow-md'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <Sparkles className="w-4 h-4 text-[#FF6B00]" />
          <span>Organization Services (Stocktake & Consultancy)</span>
        </button>

        <button
          onClick={() => setActiveTab('invoices')}
          className={`px-5 py-3 rounded-2xl font-black text-xs transition-all cursor-pointer flex items-center gap-2 whitespace-nowrap relative ${
            activeTab === 'invoices'
              ? 'bg-[#1F242D] text-white shadow-md'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <FileText className="w-4 h-4 text-[#FF6B00]" />
          <span>Invoices & Payment History</span>
          {unpaidInvoices.length > 0 && (
            <span className="w-2 h-2 rounded-full bg-[#FF6B00] animate-ping" />
          )}
        </button>

        <button
          onClick={() => setActiveTab('console')}
          className={`px-5 py-3 rounded-2xl font-black text-xs transition-all cursor-pointer flex items-center gap-2 whitespace-nowrap ${
            activeTab === 'console'
              ? 'bg-[#1F242D] text-white shadow-md'
              : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
          }`}
        >
          <Sliders className="w-4 h-4 text-[#FF6B00]" />
          <span>Console Plan Management</span>
        </button>
      </div>

      {/* TAB 1: SUBSCRIPTION PLANS & EXPIRY */}
      {activeTab === 'subscription' && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
            <div>
              <h2 className="text-lg font-black text-slate-900">Available Platform Plans</h2>
              <p className="text-xs text-slate-500">
                Each plan includes a monthly or annual expiry period. Invoices are auto-generated 7 days before expiry.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {plans.map(plan => {
              const isCurrent = subscription?.planId === plan.id;
              const warehouseAllowance = getBaseResourceAllowance(plan, 'warehouse');
              const terminalAllowance = getBaseResourceAllowance(plan, 'terminal');
              return (
                <div
                  key={plan.id}
                  className={`bg-white rounded-3xl border p-6 flex flex-col justify-between transition-all relative ${
                    isCurrent
                      ? 'border-2 border-[#FF6B00] shadow-xl ring-4 ring-[#FF6B00]/10'
                      : 'border-slate-200 hover:border-slate-300 shadow-sm'
                  }`}
                >
                  {plan.isPopular && (
                    <span className="absolute -top-3 right-6 px-3 py-1 bg-[#FF6B00] text-white font-black rounded-full text-[10px] uppercase tracking-wider shadow-md">
                      POPULAR CHOICE
                    </span>
                  )}

                  <div className="space-y-4">
                    <div className="flex justify-between items-start">
                      <div>
                        <h3 className="font-black text-base text-slate-900">{plan.name}</h3>
                        <p className="text-xs text-slate-500 mt-1 min-h-[32px]">{plan.description}</p>
                      </div>
                    </div>

                    <div className="pt-2 border-t border-slate-100">
                      <div className="flex items-baseline gap-1">
                        <span className="text-3xl font-black text-slate-900 font-mono">${plan.priceMonthly}</span>
                        <span className="text-xs text-slate-500 font-medium">/ month</span>
                      </div>
                      <p className="text-[11px] text-slate-400 font-mono mt-0.5">
                        Expiry Period: {plan.billingPeriodMonths || 1} Month(s)
                      </p>
                    </div>

                    <div className="space-y-2 pt-2">
                      <p className="text-[11px] font-bold text-slate-900 uppercase tracking-wider">Features & Entitlements:</p>
                      <p className="text-[11px] font-semibold text-slate-500">
                        {warehouseAllowance} warehouse{warehouseAllowance === 1 ? '' : 's'} ·{' '}
                        {plan.maxBranches} branch{plan.maxBranches === 1 ? '' : 'es'} ·{' '}
                        {terminalAllowance} POS terminal{terminalAllowance === 1 ? '' : 's'}
                      </p>
                      <div className="space-y-1.5 text-xs text-slate-700">
                        {plan.features.map((feat, idx) => (
                          <div key={idx} className="flex items-center gap-2">
                            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                            <span>{feat}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="pt-6 mt-6 border-t border-slate-100">
                    {isCurrent ? (
                      <div className="w-full py-3 bg-emerald-50 border border-emerald-200 text-emerald-800 font-black rounded-2xl text-xs text-center flex items-center justify-center gap-2">
                        <ShieldCheck className="w-4 h-4 text-emerald-600" />
                        <span>Current Active Plan</span>
                      </div>
                    ) : (
                      <button
                        onClick={() => handleSelectPlan(plan, plan.billingPeriodMonths || 1)}
                        className="w-full py-3 bg-[#1F242D] hover:bg-slate-800 text-white font-black rounded-2xl text-xs transition-all cursor-pointer flex items-center justify-center gap-2 shadow-md active:scale-95"
                      >
                        <span>Switch to {plan.name}</span>
                        <ArrowRight className="w-4 h-4 text-[#FF6B00]" />
                      </button>
                    )}
                  </div>

                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* TAB 2: ORGANIZATION SERVICES */}
      {activeTab === 'services' && (
        <div className="space-y-6">
          <div className="p-6 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-white rounded-3xl shadow-xl space-y-2">
            <div className="flex items-center gap-2 text-[#FF6B00]">
              <Sparkles className="w-5 h-5" />
              <span className="font-black text-xs uppercase tracking-wider">Direct Organization Services</span>
            </div>
            <h2 className="text-xl font-black text-white">Professional Stocktake, Consultancy & Hardware Services</h2>
            <p className="text-xs text-slate-300 max-w-2xl leading-relaxed">
              Order certified physical stocktake audits, retail strategy consultancy sessions, and thermal printer hardware setups directly from our technical team. Booking a service generates an official invoice.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {DEFAULT_ORGANIZATION_SERVICES.map(srv => (
              <div
                key={srv.id}
                className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm hover:shadow-md transition-all flex flex-col justify-between space-y-4"
              >
                <div className="space-y-3">
                  <div className="flex justify-between items-start gap-2">
                    <div className="flex items-center gap-3">
                      <div className="p-3 bg-orange-50 border border-orange-200 text-[#FF6B00] rounded-2xl">
                        {srv.category === 'stocktake' && <Boxes className="w-6 h-6" />}
                        {srv.category === 'consultancy' && <BarChart className="w-6 h-6" />}
                        {srv.category === 'hardware' && <Wrench className="w-6 h-6" />}
                        {srv.category === 'support' && <ShieldCheck className="w-6 h-6" />}
                      </div>
                      <div>
                        <h3 className="font-black text-base text-slate-900">{srv.title}</h3>
                        <span className="text-[10px] font-bold text-slate-400 capitalize">{srv.category} Service</span>
                      </div>
                    </div>

                    <div className="text-right">
                      <span className="text-2xl font-black text-slate-900 font-mono">${srv.price}</span>
                      <p className="text-[10px] text-slate-500 font-medium">
                        {srv.priceType === 'monthly' ? 'per month' : 'one-time fee'}
                      </p>
                    </div>
                  </div>

                  <p className="text-xs text-slate-600 leading-relaxed">{srv.description}</p>

                  <div className="space-y-1.5 pt-2">
                    <p className="text-[11px] font-bold text-slate-900 uppercase tracking-wider">Service Deliverables:</p>
                    <div className="bg-slate-50 p-3 rounded-2xl border border-slate-200 space-y-1">
                      {srv.deliverables.map((deliv, idx) => (
                        <div key={idx} className="flex items-center gap-2 text-xs text-slate-700">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                          <span>{deliv}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                <button
                  onClick={() => {
                    setSelectedServiceForOrder(srv);
                    setIsServiceOrderModalOpen(true);
                  }}
                  className="w-full py-3 bg-[#FF6B00] hover:bg-[#e66000] text-white font-black rounded-2xl text-xs transition-all cursor-pointer flex items-center justify-center gap-2 shadow-lg active:scale-95 mt-4"
                >
                  <Sparkles className="w-4 h-4" />
                  <span>Book Service & Generate Invoice (${srv.price})</span>
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 3: INVOICES & PAYMENT HISTORY */}
      {activeTab === 'invoices' && (
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <div>
              <h2 className="text-lg font-black text-slate-900">Invoices & Financial Ledger</h2>
              <p className="text-xs text-slate-500">Official record of plan renewals, 7-day auto-invoices, and organization service bookings.</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-[#1F242D] text-white text-[10px] uppercase font-bold tracking-wider">
                  <tr>
                    <th className="p-4">Invoice #</th>
                    <th className="p-4">Issue Date</th>
                    <th className="p-4">Due Date</th>
                    <th className="p-4">Primary Line Item</th>
                    <th className="p-4 text-right">Total Amount</th>
                    <th className="p-4 text-center">Status</th>
                    <th className="p-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium text-slate-700">
                  {invoices.length === 0 ? (
                    <tr>
                      <td colSpan={7} className="p-8 text-center text-slate-400">
                        No invoices generated yet.
                      </td>
                    </tr>
                  ) : (
                    invoices.map(inv => {
                      const isPaid = inv.status === 'paid';
                      return (
                        <tr key={inv.id} className="hover:bg-slate-50 transition-colors">
                          <td className="p-4 font-mono font-bold text-slate-900">
                            <div className="flex items-center gap-2">
                              <span>{inv.invoiceNumber}</span>
                              {inv.is7DayAutoGenerated && (
                                <span className="px-1.5 py-0.5 bg-amber-100 text-amber-800 text-[9px] font-bold rounded">
                                  7-Day Auto
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="p-4 text-slate-600">{new Date(inv.issueDate).toLocaleDateString()}</td>
                          <td className="p-4 font-bold text-slate-800">{new Date(inv.dueDate).toLocaleDateString()}</td>
                          <td className="p-4 font-bold text-slate-900 max-w-xs truncate">
                            {inv.items[0]?.description || 'Vendor Services'}
                          </td>
                          <td className="p-4 text-right font-mono font-black text-slate-900">
                            ${inv.totalAmount.toFixed(2)}
                          </td>
                          <td className="p-4 text-center">
                            <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase ${
                              isPaid
                                ? 'bg-emerald-100 text-emerald-800'
                                : 'bg-amber-100 text-amber-800 border border-amber-300 animate-pulse'
                            }`}>
                              {isPaid ? 'PAID' : 'UNPAID DUE'}
                            </span>
                          </td>
                          <td className="p-4 text-right">
                            <button
                              onClick={() => {
                                setSelectedInvoice(inv);
                                setIsInvoiceModalOpen(true);
                              }}
                              className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold rounded-xl text-xs transition-all cursor-pointer inline-flex items-center gap-1.5"
                            >
                              <FileText className="w-3.5 h-3.5 text-[#FF6B00]" />
                              <span>View / Pay</span>
                            </button>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: CONSOLE PLAN MANAGEMENT */}
      {activeTab === 'console' && (
        <div className="space-y-6">
          <div className="p-5 bg-slate-900 text-white rounded-3xl border border-slate-800 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-[#FF6B00] text-white rounded-2xl">
                <Sliders className="w-6 h-6" />
              </div>
              <div>
                <h2 className="text-base font-black text-white">Platform Console Admin Control Panel</h2>
                <p className="text-xs text-slate-400">
                  Control vendor subscription plans, update pricing, monthly expiry durations, and feature capabilities.
                </p>
              </div>
            </div>

            <button
              onClick={() => {
                setEditingConsolePlan(null);
                setIsConsoleModalOpen(true);
              }}
              className="px-5 py-2.5 bg-[#FF6B00] hover:bg-[#e66000] text-white font-black rounded-2xl text-xs flex items-center gap-2 shadow-lg transition-all cursor-pointer shrink-0"
            >
              <Plus className="w-4 h-4" />
              <span>Create New Console Plan</span>
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {plans.map(plan => (
              <div key={plan.id} className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="font-black text-base text-slate-900">{plan.name}</h3>
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase ${
                      plan.status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600'
                    }`}>
                      {plan.status}
                    </span>
                  </div>
                  <span className="text-2xl font-black text-slate-900 font-mono">${plan.priceMonthly}</span>
                </div>

                <p className="text-xs text-slate-500">{plan.description}</p>

                <div className="text-xs space-y-1 bg-slate-50 p-3 rounded-2xl border border-slate-200">
                  <p>Expiry Period: <strong>{plan.billingPeriodMonths || 1} Month(s)</strong></p>
                  <p>Max Branches: <strong>{plan.maxBranches}</strong></p>
                  <p>Max Staff: <strong>{plan.maxStaff}</strong></p>
                </div>

                <button
                  onClick={() => {
                    setEditingConsolePlan(plan);
                    setIsConsoleModalOpen(true);
                  }}
                  className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold rounded-xl text-xs transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <Sliders className="w-3.5 h-3.5 text-[#FF6B00]" />
                  <span>Configure Plan Parameters</span>
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* MODALS */}
      <InvoiceModal
        isOpen={isInvoiceModalOpen}
        onClose={() => setIsInvoiceModalOpen(false)}
        invoice={selectedInvoice}
        vendor={vendor}
        onPayInvoice={handlePayInvoice}
      />

      <ConsolePlanModal
        isOpen={isConsoleModalOpen}
        onClose={() => setIsConsoleModalOpen(false)}
        editingPlan={editingConsolePlan}
        onSavePlan={handleSaveConsolePlan}
      />

      <ServiceOrderModal
        isOpen={isServiceOrderModalOpen}
        onClose={() => setIsServiceOrderModalOpen(false)}
        service={selectedServiceForOrder}
        vendor={vendor}
        branches={branches}
        onRequestService={handleOrderService}
      />

    </div>
  );
};
