import assert from 'node:assert/strict'; import {after,before,test} from 'node:test';
import {assertFails,initializeTestEnvironment,type RulesTestEnvironment} from '@firebase/rules-unit-testing';
import {initializeApp,deleteApp,type FirebaseApp} from 'firebase/app'; import {connectAuthEmulator,createUserWithEmailAndPassword,getAuth} from 'firebase/auth';
import {connectFunctionsEmulator,getFunctions,httpsCallable} from 'firebase/functions'; import {collection,doc,getDoc,getDocs,setDoc} from 'firebase/firestore';
const projectId='demo-itred-stocktake-test'; let env:RulesTestEnvironment; let counterApp:FirebaseApp,approverApp:FirebaseApp,anonApp:FirebaseApp; let counterUid='',approverUid=''; let seq=0;
const fn=(app:FirebaseApp,name:string)=>(data:Record<string,unknown>)=>httpsCallable<Record<string,unknown>,any>(getFunctions(app,'us-central1'),name)(data);
async function adminSet(path:string,value:any){await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),path),value))} async function adminGet(path:string){let value:any;await env.withSecurityRulesDisabled(async c=>{value=(await getDoc(doc(c.firestore(),path))).data()});return value}
async function reject(p:Promise<any>,code:string){await assert.rejects(p,e=>String((e as any).code).endsWith(code))}
async function seed(opts:any={}){const n=++seq,v=`v${n}`,loc=`loc${n}`,product=`p${n}`,id=`st${n}`,now=new Date().toISOString(),type=opts.type||'WAREHOUSE';for(const [uid,permissions] of [[counterUid,['stocktake.count','inventory.adjust']],[approverUid,['stocktake.approve','inventory.adjust']]] as any)await adminSet(`vendors/${v}/memberships/${uid}`,{tenantId:opts.wrongTenant&&uid===counterUid?'wrong':v,vendorId:v,userUid:uid,status:'ACTIVE',roleId:uid===counterUid?'counter':'approver',permissions:opts.noPermission&&uid===counterUid?[]:permissions,assignedWarehouseIds:opts.unassigned?[]:[loc],assignedBranchIds:opts.unassigned?[]:[loc]});await adminSet(`vendors/${v}/${type==='WAREHOUSE'?'warehouses':'branches'}/${loc}`,{id:loc,tenantId:v,vendorId:v,name:'Location',code:loc,status:opts.status||'active',licenseStatus:opts.licence||'licensed',createdAt:now});await adminSet(`vendors/${v}/products/${product}`,{id:product,tenantId:v,vendorId:v,status:'active'});const bid=`${v}::${v}::${loc}::${product}`;await adminSet(`vendors/${v}/inventory_balances/${bid}`,{id:bid,tenantId:v,vendorId:v,stockLocationId:loc,productId:product,onHandQty:opts.quantity??10,reservedQty:0,inTransitQty:0,quarantinedQty:0,damagedQty:0,version:opts.version??1,updatedAt:now});await adminSet(`vendors/${v}/${type==='WAREHOUSE'?'warehouse_inventory':'branch_inventory'}/${v}_${loc}_${product}`,{id:`${v}_${loc}_${product}`,tenantId:v,vendorId:v,[type==='WAREHOUSE'?'warehouseId':'branchId']:loc,productId:product,quantity:opts.quantity??10,version:opts.version??1,lastUpdated:now});return{v,loc,product,id,type,bid}}
async function create(s:any,app=counterApp,blind=true){return(await fn(app,'createStocktake')({vendorId:s.v,stocktakeId:s.id,locationId:s.loc,locationType:s.type,blindCount:blind,commandId:`create:${s.id}`})).data} async function open(s:any){return(await fn(counterApp,'openStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:`open:${s.id}`})).data} async function count(s:any,q:number,event=`ev:${s.id}`,cmd=`count:${event}`){return(await fn(counterApp,'submitStocktakeCount')({vendorId:s.v,stocktakeId:s.id,productId:s.product,countedQuantity:q,countEventId:event,commandId:cmd,offlineEvent:true,deviceId:'device'})).data} async function approveReady(s:any,q:number){await create(s);await open(s);await count(s,q);await fn(counterApp,'submitStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:`submit:${s.id}`});await fn(approverApp,'approveStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:`approve:${s.id}`})} async function post(s:any,extra:any={}){return(await fn(approverApp,'postStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`post:${s.id}`,...extra})).data}
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8080}});counterApp=initializeApp({projectId,apiKey:'x'},'counter');approverApp=initializeApp({projectId,apiKey:'x'},'approver');anonApp=initializeApp({projectId,apiKey:'x'},'anon');for(const app of [counterApp,approverApp]){const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});const user=await createUserWithEmailAndPassword(auth,`${app.name}@test.local`,'password123');if(app===counterApp)counterUid=user.user.uid;else approverUid=user.user.uid}for(const app of [counterApp,approverApp,anonApp])connectFunctionsEmulator(getFunctions(app,'us-central1'),'127.0.0.1',5001)});after(async()=>{await env.cleanup();await Promise.all([deleteApp(counterApp),deleteApp(approverApp),deleteApp(anonApp)])});
test('01 unauthenticated command rejected',async()=>{const s=await seed();await reject(create(s,anonApp),'unauthenticated')});
test('02 non-member rejected',async()=>{const s=await seed();await reject(create({...s,v:'missing'}),'permission-denied')});
test('03 wrong tenant rejected',async()=>{const s=await seed({wrongTenant:true});await reject(create(s),'permission-denied')});
test('04 unauthorized location rejected',async()=>{const s=await seed({unassigned:true});await reject(create(s),'permission-denied')});
test('05 inactive location rejected',async()=>{const s=await seed({status:'suspended'});await reject(create(s),'failed-precondition')});
test('06 unlicensed location rejected',async()=>{const s=await seed({licence:'unlicensed'});await reject(create(s),'failed-precondition')});
test('07 warehouse stocktake creation succeeds',async()=>{const s=await seed();assert.equal((await create(s)).locationType,'WAREHOUSE')});
test('08 branch stocktake creation succeeds',async()=>{const s=await seed({type:'BRANCH'});assert.equal((await create(s)).locationType,'BRANCH')});
test('09 terminal location rejected',async()=>{const s=await seed();await reject(fn(counterApp,'createStocktake')({vendorId:s.v,stocktakeId:s.id,locationId:s.loc,locationType:'TERMINAL',commandId:'terminal'}),'invalid-argument')});
test('10 count evidence persists',async()=>{const s=await seed();await create(s);await open(s);await count(s,12);assert.equal((await adminGet(`vendors/${s.v}/stocktake_count_evidence/ev_${s.id}`)).countedQuantity,12)});
test('11 duplicate count command is idempotent',async()=>{const s=await seed();await create(s);await open(s);await count(s,11);await count(s,11);let q:any;await env.withSecurityRulesDisabled(async c=>{q=await getDocs(collection(c.firestore(),`vendors/${s.v}/stocktake_count_evidence`))});assert.equal(q.size,1)});
test('12 recount preserves prior evidence',async()=>{const s=await seed();await create(s);await open(s);await count(s,11,`first:${s.id}`);await count(s,12,`second:${s.id}`);assert.ok(await adminGet(`vendors/${s.v}/stocktake_count_evidence/first_${s.id}`));assert.ok(await adminGet(`vendors/${s.v}/stocktake_count_evidence/second_${s.id}`))});
test('13 blind count hides system quantity',async()=>{const s=await seed();await create(s);await open(s);assert.equal((await count(s,12)).systemQuantitySnapshot,null)});
test('14 server calculates variance',async()=>{const s=await seed();await create(s,counterApp,false);await open(s);assert.equal((await count(s,13)).varianceQuantity,3)});
test('15 unauthorized approval rejected',async()=>{const s=await seed();await create(s);await open(s);await count(s,10);await fn(counterApp,'submitStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:'submit'});await reject(fn(counterApp,'approveStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:'approve'}),'permission-denied')});
test('16 self approval blocked',async()=>{const s=await seed();await adminSet(`vendors/${s.v}/memberships/${counterUid}`,{...(await adminGet(`vendors/${s.v}/memberships/${counterUid}`)),permissions:['stocktake.count','stocktake.approve']});await create(s);await open(s);await count(s,10);await fn(counterApp,'submitStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:'submit'});await reject(fn(counterApp,'approveStocktake')({vendorId:s.v,stocktakeId:s.id,commandId:'approve'}),'permission-denied')});
test('17 zero variance creates no movement',async()=>{const s=await seed();await approveReady(s,10);const x=await post(s);assert.equal(x.movementIds.length,0)});
test('18 positive variance posts one increase',async()=>{const s=await seed();await approveReady(s,13);await post(s);assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,13)});
test('19 negative variance posts one decrease',async()=>{const s=await seed();await approveReady(s,7);await post(s);assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,7)});
test('20 duplicate posting is idempotent',async()=>{const s=await seed();await approveReady(s,12);await post(s);await post(s);assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,12)});
test('21 injected posting failure rolls back',async()=>{const s=await seed();await approveReady(s,12);await reject(post(s,{testFailurePoint:'AFTER_INVENTORY'}),'aborted');assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,10)});
test('22 stale version rejected',async()=>{const s=await seed();await approveReady(s,12);await adminSet(`vendors/${s.v}/inventory_balances/${s.bid}`,{...(await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)),version:2});await reject(post(s),'aborted')});
test('23 concurrent movement detected',async()=>{const s=await seed();await approveReady(s,12);await adminSet(`vendors/${s.v}/inventory_balances/${s.bid}`,{...(await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)),onHandQty:9,version:2});await reject(post(s),'aborted')});
test('24 valid reversal compensates movement',async()=>{const s=await seed();await approveReady(s,12);await post(s);await fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse:${s.id}`,reason:'Correction'});assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,10)});
test('25 original movement remains immutable',async()=>{const s=await seed();await approveReady(s,12);const x=await post(s),before=await adminGet(`vendors/${s.v}/inventory_movements/${x.movementIds[0]}`);await fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse:${s.id}`,reason:'Correction'});assert.deepEqual(await adminGet(`vendors/${s.v}/inventory_movements/${x.movementIds[0]}`),before)});
test('26 over reversal rejected',async()=>{const s=await seed();await approveReady(s,12);await post(s);await fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse:${s.id}`,reason:'Correction'});await reject(fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse2:${s.id}`,reason:'Again'}),'failed-precondition')});
test('27 duplicate reversal idempotent',async()=>{const s=await seed();await approveReady(s,12);await post(s);const p={vendorId:s.v,stocktakeId:s.id,commandId:`reverse:${s.id}`,reason:'Correction'};await fn(approverApp,'reverseStocktakeAdjustment')(p);await fn(approverApp,'reverseStocktakeAdjustment')(p);assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,10)});
test('28 browser authoritative writes denied',async()=>{const s=await seed();const client=env.authenticatedContext(counterUid).firestore();await assertFails(setDoc(doc(client,`vendors/${s.v}/stocktakes/forged`),{vendorId:s.v,locationId:s.loc}));await assertFails(setDoc(doc(client,`vendors/${s.v}/stocktake_commands/forged`),{}));await assertFails(setDoc(doc(client,`vendors/${s.v}/stocktake_count_evidence/forged`),{}))});
test('29 canonical audit and BI events once',async()=>{const s=await seed();await approveReady(s,12);await post(s);let a:any,b:any;await env.withSecurityRulesDisabled(async c=>{a=await getDocs(collection(c.firestore(),`vendors/${s.v}/audit_events`));b=await getDocs(collection(c.firestore(),`vendors/${s.v}/bi_events`))});assert.equal(a.size,b.size);assert.ok(a.size>=6)});
test('30 partial reversal preserves remaining authority',async()=>{const s=await seed();await approveReady(s,14);const posted=await post(s),movementId=posted.movementIds[0];const first=(await fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse-partial:${s.id}`,reason:'Partial correction',quantities:{[movementId]:2}})).data;assert.equal(first.status,'PARTIALLY_REVERSED');assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,12);const second=(await fn(approverApp,'reverseStocktakeAdjustment')({vendorId:s.v,stocktakeId:s.id,commandId:`reverse-rest:${s.id}`,reason:'Complete correction'})).data;assert.equal(second.status,'REVERSED');assert.equal((await adminGet(`vendors/${s.v}/inventory_balances/${s.bid}`)).onHandQty,10);assert.equal(second.reversalHistory.length,2)});
