import ExcelJS from 'exceljs';
import { CANONICAL_PRODUCT_HEADERS, PRODUCT_IMPORT_SCHEMA_VERSION, PRODUCT_IMPORT_TEMPLATE_NAME, PRODUCT_IMPORT_TEMPLATE_VERSION, ProductImportLocation } from './domain';

export interface ProductTemplateOptions { tenantId?: string; applicationVersion?: string; categories: string[]; locations: ProductImportLocation[]; }

function download(blob: Blob, name: string): void {
  const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}

export function exportProductCsvTemplate(): void {
  const csv = `${CANONICAL_PRODUCT_HEADERS.map(value => `"${value.replace(/"/g, '""')}"`).join(',')}\r\n`;
  download(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' }), 'itred-product-import-template.csv');
}

export function createProductTemplateWorkbook(options: ProductTemplateOptions): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'iTred Commerce POS'; workbook.created = new Date();
  const products = workbook.addWorksheet('Products', { views: [{ state: 'frozen', ySplit: 1 }] });
  products.addRow([...CANONICAL_PRODUCT_HEADERS]); products.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; products.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F242D' } };
  products.columns = CANONICAL_PRODUCT_HEADERS.map(header => ({ header, key: header, width: Math.max(12, header.length + 2) }));
  const instructions = workbook.addWorksheet('Instructions');
  [['iTred Product Import Instructions'], ['Do not rename, reorder, add or remove columns.'], ['Only CSV and XLSX templates generated by iTred are accepted.'], ['Quantity is posted as an opening-balance request and never changes stock until approval.']].forEach(row => instructions.addRow(row));
  const reference = workbook.addWorksheet('Reference Data'); reference.addRow(['Product Types', 'Units of Measure', 'Categories', 'Location Codes']);
  const types = ['INVENTORY', 'NON_INVENTORY', 'SERVICE', 'BOM', 'OTHER']; const units = ['pcs', 'each', 'box', 'pack', 'kg', 'litre', 'metre', 'hour'];
  Array.from({ length: Math.max(types.length, units.length, options.categories.length, options.locations.length) }, (_, index) => [types[index] || '', units[index] || '', options.categories[index] || '', options.locations[index]?.code || '']).forEach(row => reference.addRow(row));
  for (let row = 2; row <= 1000; row += 1) {
    products.getCell(`L${row}`).dataValidation = { type: 'list', allowBlank: false, formulae: ["'Reference Data'!$A$2:$A$6"] };
    products.getCell(`I${row}`).dataValidation = { type: 'list', allowBlank: false, formulae: ["'Reference Data'!$B$2:$B$9"] };
    if (options.categories.length) products.getCell(`D${row}`).dataValidation = { type: 'list', allowBlank: false, formulae: [`'Reference Data'!$C$2:$C$${options.categories.length + 1}`] };
    if (options.locations.length) products.getCell(`J${row}`).dataValidation = { type: 'list', allowBlank: true, formulae: [`'Reference Data'!$D$2:$D$${options.locations.length + 1}`] };
  }
  const metadata = workbook.addWorksheet('_Template_Metadata', { state: 'veryHidden' });
  [['templateName', PRODUCT_IMPORT_TEMPLATE_NAME], ['templateVersion', PRODUCT_IMPORT_TEMPLATE_VERSION], ['schemaVersion', PRODUCT_IMPORT_SCHEMA_VERSION], ['generatedAt', new Date().toISOString()], ['tenantId', options.tenantId || ''], ['applicationVersion', options.applicationVersion || '']].forEach(row => metadata.addRow(row));
  return workbook;
}

export async function exportProductXlsxTemplate(options: ProductTemplateOptions): Promise<void> {
  const data = await createProductTemplateWorkbook(options).xlsx.writeBuffer();
  download(new Blob([data as BlobPart], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'itred-product-import-template.xlsx');
}
