import React, { useEffect, useMemo, useState } from 'react';
import { Building2, CalendarDays, Plus, Search, Send, Trash2 } from 'lucide-react';
import { Product, PurchaseOrderItem, StaffMember, Supplier, Warehouse } from '../../types';
import { CreatePurchaseOrderInput } from '../../services/db';
import { searchReceivingProducts } from '../../services/supplierReceiving';
import { Modal } from '../Common/Modal';
import { AddSupplierModal } from '../Suppliers/AddSupplierModal';

type Line = Omit<PurchaseOrderItem, 'receivedQuantity'>;
interface Props { isOpen: boolean; onClose: () => void; vendorId: string; businessName: string; currency: string; products: Product[]; systemQuantities: Record<string, number>; suppliers: Supplier[]; setSuppliers: React.Dispatch<React.SetStateAction<Supplier[]>>; warehouses: Warehouse[]; activeStaff: StaffMember; source: 'PLANNED'|'BI_RECOMMENDATION'; initialLines?: Line[]; onSubmit: (input: CreatePurchaseOrderInput) => Promise<void>; }
const today = () => new Date().toISOString().slice(0,10);

export function PurchaseOrderFormModal(props: Props) {
  const [supplierId,setSupplierId]=useState(''); const [warehouseId,setWarehouseId]=useState(''); const [orderDate,setOrderDate]=useState(today()); const [deliveryDate,setDeliveryDate]=useState('');
  const [buyerReference,setBuyerReference]=useState(''); const [quotation,setQuotation]=useState(''); const [paymentTerms,setPaymentTerms]=useState('30 days'); const [deliveryTerms,setDeliveryTerms]=useState('Deliver to destination warehouse'); const [shippingAddress,setShippingAddress]=useState(''); const [billingAddress,setBillingAddress]=useState(''); const [notes,setNotes]=useState('');
  const [query,setQuery]=useState(''); const [lines,setLines]=useState<Line[]>([]); const [addSupplierOpen,setAddSupplierOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{ if(!props.isOpen)return; setSupplierId(props.suppliers[0]?.id||''); const warehouse=props.warehouses.find(item=>item.isDefault)||props.warehouses[0]; setWarehouseId(warehouse?.id||''); setShippingAddress(warehouse?.location||''); setOrderDate(today()); setDeliveryDate(''); setBuyerReference(''); setQuotation(''); setNotes(''); setLines(props.initialLines||[]); setError(''); },[props.isOpen,props.initialLines,props.suppliers,props.warehouses]);
  const supplier=props.suppliers.find(item=>item.id===supplierId); const warehouse=props.warehouses.find(item=>item.id===warehouseId); const results=useMemo(()=>searchReceivingProducts(props.products,query).slice(0,8),[props.products,query]);
  const add=(product:Product)=>{setLines(current=>current.some(item=>item.productId===product.id)?current:[...current,{productId:product.id,productName:product.name,sku:product.sku,orderedQuantity:1,unitCost:product.costPrice,unitOfMeasure:product.unitOfMeasure||product.unit,discountPercent:0,taxRate:0}]);setQuery('');};
  const lineNet=(line:Line)=>line.orderedQuantity*line.unitCost*(1-(line.discountPercent||0)/100); const subtotal=lines.reduce((sum,line)=>sum+lineNet(line),0); const tax=lines.reduce((sum,line)=>sum+lineNet(line)*(line.taxRate||0)/100,0); const total=subtotal+tax;
  const update=(index:number,patch:Partial<Line>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...patch}:line));
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!supplier)return setError('Select a supplier.');if(!warehouse)return setError('Select a destination warehouse.');if(!lines.length)return setError('Add at least one product.');if(deliveryDate&&deliveryDate<orderDate)return setError('Expected delivery date cannot be before the order date.');setBusy(true);setError('');try{await props.onSubmit({supplierId:supplier.id,supplierName:supplier.name,supplierAddress:supplier.fullAddress,supplierPhone:supplier.phone,supplierBusinessNumber:supplier.businessNumber,supplierTaxNumber:supplier.taxNumber,source:props.source,notes,items:lines,requester:{id:props.activeStaff.id,name:props.activeStaff.name,role:props.activeStaff.role},orderDate,expectedDeliveryDate:deliveryDate,destinationWarehouseId:warehouse.id,destinationWarehouseName:warehouse.name,buyerReference,supplierQuotationNumber:quotation,paymentTerms,deliveryTerms,currency:props.currency,shippingAddress,billingAddress});props.onClose();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to submit purchase order.');}finally{setBusy(false);}};
  const field='mt-1 w-full rounded border border-slate-300 px-3 py-2 text-xs focus:border-[#FF6600] focus:outline-none';
  return <><Modal isOpen={props.isOpen} onClose={props.onClose} title={props.source==='PLANNED'?'Planned Purchase Order':'BI Recommended Purchase Order'} subtitle="Controlled supplier order · management approval required · no inventory movement" maxWidth="4xl"><form onSubmit={submit} className="space-y-5">
    {error&&<p className="border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}
    <section className="grid gap-4 border p-4 lg:grid-cols-2"><div><h3 className="mb-2 flex items-center gap-2 font-black"><Building2 className="h-4 text-[#FF6600]"/>Supplier Details</h3><label className="text-xs font-bold">Supplier *<select value={supplierId} onChange={e=>e.target.value==='__new__'?setAddSupplierOpen(true):setSupplierId(e.target.value)} className={field}><option value="">Select supplier</option><option value="__new__">＋ Add New Supplier…</option>{props.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{supplier&&<dl className="mt-3 grid grid-cols-[8rem_1fr] gap-1 rounded bg-slate-50 p-3 text-xs"><dt>Address</dt><dd className="font-bold">{supplier.fullAddress||'Not recorded'}</dd><dt>Phone</dt><dd>{supplier.phone||'Not recorded'}</dd><dt>Business No.</dt><dd>{supplier.businessNumber||'Not recorded'}</dd><dt>Tax No.</dt><dd>{supplier.taxNumber||'Not recorded'}</dd></dl>}</div><div><h3 className="mb-2 flex items-center gap-2 font-black"><CalendarDays className="h-4 text-[#FF6600]"/>Order Control</h3><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Order Date *<input required type="date" value={orderDate} onChange={e=>setOrderDate(e.target.value)} className={field}/></label><label className="text-xs font-bold">Expected Delivery<input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)} className={field}/></label><label className="text-xs font-bold">Buyer Reference<input value={buyerReference} onChange={e=>setBuyerReference(e.target.value)} className={field}/></label><label className="text-xs font-bold">Supplier Quotation No.<input value={quotation} onChange={e=>setQuotation(e.target.value)} className={field}/></label></div></div></section>
    <section className="grid gap-3 border p-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">Destination Warehouse *<select required value={warehouseId} onChange={e=>{setWarehouseId(e.target.value);setShippingAddress(props.warehouses.find(item=>item.id===e.target.value)?.location||'');}} className={field}><option value="">Select warehouse</option>{props.warehouses.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label className="text-xs font-bold">Payment Terms<input value={paymentTerms} onChange={e=>setPaymentTerms(e.target.value)} className={field}/></label><label className="text-xs font-bold">Delivery Terms<input value={deliveryTerms} onChange={e=>setDeliveryTerms(e.target.value)} className={field}/></label><label className="text-xs font-bold">Currency<input disabled value={props.currency} className={`${field} bg-slate-100`}/></label><label className="text-xs font-bold md:col-span-2">Ship To Address<textarea required value={shippingAddress} onChange={e=>setShippingAddress(e.target.value)} className={field}/></label><label className="text-xs font-bold md:col-span-2">Bill To Address<textarea value={billingAddress} onChange={e=>setBillingAddress(e.target.value)} placeholder={props.businessName} className={field}/></label></section>
    <section className="space-y-3"><div className="relative"><Search className="absolute left-3 top-3 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search SKU, product name, barcode or manufacturer code" className={`${field} pl-9`}/>{query&&results.length>0&&<div className="absolute z-20 w-full border bg-white shadow-xl">{results.map(product=><button type="button" key={product.id} onClick={()=>add(product)} className="flex w-full justify-between p-3 text-left text-xs hover:bg-orange-50"><span><b>{product.sku}</b> · {product.name}</span><Plus className="h-4"/></button>)}</div>}</div><div className="overflow-x-auto border"><table className="w-full min-w-[1050px] text-xs"><thead className="bg-[#1F242D] text-white"><tr><th className="p-2 text-left">SKU / Description</th><th>UM</th><th>System Qty</th><th>Order Qty</th><th>Unit Cost</th><th>Discount %</th><th>Tax %</th><th>Line Total</th><th/></tr></thead><tbody>{lines.map((line,index)=><tr key={line.productId} className="border-t"><td className="p-2"><b>{line.sku}</b><br/>{line.productName}</td><td className="text-center">{line.unitOfMeasure}</td><td className="text-center">—</td><td><input aria-label={`Order quantity for ${line.sku}`} type="number" min="0.01" step="0.01" value={line.orderedQuantity} onChange={e=>update(index,{orderedQuantity:Number(e.target.value)})} className="w-20 border p-1 text-right"/></td><td><input aria-label={`Unit cost for ${line.sku}`} type="number" min="0" step="0.01" value={line.unitCost} onChange={e=>update(index,{unitCost:Number(e.target.value)})} className="w-24 border p-1 text-right"/></td><td><input type="number" min="0" max="100" value={line.discountPercent||0} onChange={e=>update(index,{discountPercent:Number(e.target.value)})} className="w-16 border p-1 text-right"/></td><td><input type="number" min="0" value={line.taxRate||0} onChange={e=>update(index,{taxRate:Number(e.target.value)})} className="w-16 border p-1 text-right"/></td><td className="p-2 text-right font-bold">{props.currency}{(lineNet(line)*(1+(line.taxRate||0)/100)).toFixed(2)}</td><td><button type="button" onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}><Trash2 className="h-4 text-red-600"/></button></td></tr>)}</tbody></table>{!lines.length&&<div className="p-8 text-center text-slate-500">Search and add products to this purchase order.</div>}</div></section>
    <section className="grid gap-4 border p-4 md:grid-cols-[1fr_20rem]"><label className="text-xs font-bold">Commercial / Delivery Notes<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} className={field}/></label><dl className="space-y-2 bg-slate-50 p-3 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{props.currency}{subtotal.toFixed(2)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>{props.currency}{tax.toFixed(2)}</dd></div><div className="flex justify-between border-t pt-2 text-base font-black"><dt>PO Total</dt><dd>{props.currency}{total.toFixed(2)}</dd></div></dl></section>
    <footer className="flex justify-end gap-2"><button type="button" onClick={props.onClose} className="border px-5 py-2 text-xs font-bold">Cancel</button><button disabled={busy||!lines.length} className="flex items-center gap-2 bg-[#FF6600] px-5 py-2 text-xs font-black text-white disabled:opacity-40"><Send className="h-4"/>{busy?'Submitting…':'Send PO for Management Approval'}</button></footer>
  </form></Modal><AddSupplierModal isOpen={addSupplierOpen} onClose={()=>setAddSupplierOpen(false)} vendorId={props.vendorId} activeStaff={props.activeStaff} onCreated={created=>{props.setSuppliers(current=>[...current,created].sort((a,b)=>a.name.localeCompare(b.name)));setSupplierId(created.id);}}/></>;
}
