import type { Firestore, Transaction } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { InventoryPostingEngine } from '../../src/features/inventory/application/inventoryPostingEngine.js';
import type { InventoryRepository } from '../../src/features/inventory/application/inventoryRepository.js';
import { deterministicInventoryBalanceId, emptyInventoryBalance, type InventoryBalance, type InventoryMovement, type StockLocation } from '../../src/features/inventory/domain/index.js';

type Data = Record<string, any>;
type Membership = { tenantId:string; vendorId:string; userUid:string; status:string; roleId:string; permissions:string[]; assignedBranchIds:string[]; assignedTerminalIds:string[] };
const clean=<T>(value:T):T=>Array.isArray(value)?value.map(clean) as T:value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined).map(([k,v])=>[k,clean(v)])) as T:value;
const required=(data:Data,key:string)=>{const value=String(data[key]??'').trim();if(!value)throw new HttpsError('invalid-argument',`${key} is required.`);return value};
const safe=(value:string)=>value.replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,220);
const money=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;

function emit(tx:Transaction,db:Firestore,sale:Data,eventType:string,now:string):void {
  const id=safe(`${eventType}:${sale.commandId}`);
  const event=clean({id,eventId:id,eventType,eventVersion:1,tenantId:sale.vendorId,vendorId:sale.vendorId,branchId:sale.branchId,terminalId:sale.terminalId,cashierId:sale.cashierId,userId:sale.cashierId,shiftId:sale.shiftId,saleId:sale.saleId,commandId:sale.commandId,entityType:'SALE',entityId:sale.saleId,action:eventType,outcome:eventType==='SALE_COMPLETED'?'COMPLETED':'STARTED',amount:sale.totalAmount,currency:sale.currency,source:'POS',occurredAt:now,recordedAt:now,offlineEvent:false,correlationId:sale.saleId});
  tx.create(db.doc(`vendors/${sale.vendorId}/audit_events/${id}`),event);
  tx.create(db.doc(`vendors/${sale.vendorId}/bi_events/${id}`),event);
}

function saleRepository(tx:Transaction,db:Firestore,sale:Data,location:StockLocation,balances:Map<string,InventoryBalance>,legacy:Map<string,Data>,movements:Map<string,InventoryMovement>):InventoryRepository {
  return {
    async getStockLocation(id){return id===location.id?location:null},
    async getBalance(_tenant,_vendor,_location,productId){return balances.get(productId)||null},
    async getMovementByIdempotencyKey(_tenant,_vendor,key){return movements.get(key)||null},
    async saveMovement(movement){movements.set(movement.idempotencyKey,movement);tx.create(db.doc(`vendors/${sale.vendorId}/inventory_movements/${movement.id}`),clean(movement))},
    async saveBalance(balance){balances.set(balance.productId,balance);tx.set(db.doc(`vendors/${sale.vendorId}/inventory_balances/${balance.id}`),clean(balance));const id=`${sale.vendorId}_${sale.branchId}_${balance.productId}`;tx.set(db.doc(`vendors/${sale.vendorId}/branch_inventory/${id}`),clean({...legacy.get(balance.productId),id,tenantId:sale.vendorId,vendorId:sale.vendorId,branchId:sale.branchId,productId:balance.productId,quantity:balance.onHandQty,reservedQuantity:balance.reservedQty,inTransitQuantity:balance.inTransitQty,quarantinedQuantity:balance.quarantinedQty,damagedQuantity:balance.damagedQty,version:balance.version,lastUpdated:balance.updatedAt}))},
    async runAtomic<T>(operation:(repository:InventoryRepository)=>Promise<T>){return operation(this)},
  };
}

export function createSaleCallable(db:Firestore){
  return onCall(async request=>{
    const data=request.data as Data,vendorId=required(data,'vendorId'),saleId=required(data,'saleId'),commandId=required(data,'commandId'),branchId=required(data,'branchId'),terminalId=required(data,'terminalId'),shiftId=required(data,'shiftId');
    if(!request.auth?.uid)throw new HttpsError('unauthenticated','Firebase authentication is required.');
    const uid=request.auth.uid,rawLines=data.lines as Data[];
    if(!Array.isArray(rawLines)||!rawLines.length)throw new HttpsError('invalid-argument','Sale lines are required.');
    return db.runTransaction(async tx=>{
      const membershipSnapshot=await tx.get(db.doc(`vendors/${vendorId}/memberships/${uid}`)),member=membershipSnapshot.data() as Membership|undefined;
      if(!membershipSnapshot.exists||member?.tenantId!==vendorId||member.vendorId!==vendorId||member.userUid!==uid||member.status!=='ACTIVE')throw new HttpsError('permission-denied','Active tenant membership is required.');
      if(!member.permissions.includes('sale.complete'))throw new HttpsError('permission-denied','sale.complete is required.');
      const commandRef=db.doc(`vendors/${vendorId}/sale_commands/${safe(commandId)}`),prior=await tx.get(commandRef);
      if(prior.exists){if(prior.data()!.saleId!==saleId)throw new HttpsError('already-exists','Command identity belongs to another sale.');return prior.data()!.result}
      const saleRef=db.doc(`vendors/${vendorId}/orders/${saleId}`),existing=await tx.get(saleRef);if(existing.exists)throw new HttpsError('already-exists','Sale exists without its command receipt.');
      const [branchSnapshot,terminalSnapshot,shiftSnapshot,vendorSnapshot]=await Promise.all([tx.get(db.doc(`vendors/${vendorId}/branches/${branchId}`)),tx.get(db.doc(`vendors/${vendorId}/terminals/${terminalId}`)),tx.get(db.doc(`vendors/${vendorId}/shifts/${shiftId}`)),tx.get(db.doc(`vendors/${vendorId}`))]);
      const branch=branchSnapshot.data(),terminal=terminalSnapshot.data(),shift=shiftSnapshot.data(),vendor=vendorSnapshot.data()||{};
      if(!branchSnapshot.exists||(branch?.tenantId&&branch.tenantId!==vendorId)||branch?.vendorId!==vendorId)throw new HttpsError('failed-precondition','Sale branch is invalid.');
      if(String(branch.status).toLowerCase()!=='active')throw new HttpsError('failed-precondition','Sale branch is inactive.');
      if(String(branch.licenseStatus||branch.licenceStatus).toLowerCase()!=='licensed')throw new HttpsError('failed-precondition','Sale branch is unlicensed.');
      if(!member.permissions.includes('location.all')&&!member.assignedBranchIds?.includes(branchId))throw new HttpsError('permission-denied','Branch assignment is required.');
      if(!terminalSnapshot.exists||terminal?.vendorId!==vendorId||terminal?.branchId!==branchId)throw new HttpsError('failed-precondition','Terminal is not assigned to the sale branch.');
      if(String(terminal.status).toLowerCase()!=='active'||String(terminal.licenseStatus||terminal.licenceStatus).toLowerCase()!=='licensed')throw new HttpsError('failed-precondition','Terminal must be active and licensed.');
      if(!member.permissions.includes('location.all')&&member.assignedTerminalIds?.length&&!member.assignedTerminalIds.includes(terminalId))throw new HttpsError('permission-denied','Terminal assignment is required.');
      if(!shiftSnapshot.exists||shift?.vendorId!==vendorId||shift?.branchId!==branchId||shift?.terminalId!==terminalId||String(shift.status).toLowerCase()!=='open')throw new HttpsError('failed-precondition','An open branch and terminal shift is required.');
      if(shift.userUid!==uid&&shift.staffId!==uid)throw new HttpsError('permission-denied','The authenticated cashier does not own the active shift.');

      const aggregate=new Map<string,{productId:string;quantity:number;discount:number;clientPrice?:number}>();
      for(const raw of rawLines){const productId=required(raw,'productId'),quantity=Number(raw.quantity),discount=Number(raw.discount||0);if(!Number.isInteger(quantity)||quantity<=0||!Number.isFinite(discount)||discount<0)throw new HttpsError('invalid-argument','Sale quantities and discounts are invalid.');const old=aggregate.get(productId);aggregate.set(productId,{productId,quantity:(old?.quantity||0)+quantity,discount:money((old?.discount||0)+discount),clientPrice:raw.unitPrice===undefined?old?.clientPrice:Number(raw.unitPrice)})}
      const productIds=[...aggregate.keys()],productSnapshots=await Promise.all(productIds.map(id=>tx.get(db.doc(`vendors/${vendorId}/products/${id}`)))),now=new Date().toISOString(),currency=String(vendor.currency||'USD'),lines:Data[]=[];
      for(let index=0;index<productIds.length;index++){const product=productSnapshots[index].data(),requested=aggregate.get(productIds[index])!;if(!productSnapshots[index].exists||(product?.tenantId&&product.tenantId!==vendorId)||product?.vendorId!==vendorId)throw new HttpsError('failed-precondition','Sale product is invalid.');if(String(product.status||'active').toLowerCase()!=='active'||String(product.productType||'INVENTORY')!=='INVENTORY')throw new HttpsError('failed-precondition','Sale product is not active inventory.');const unitPrice=money(Number(product.branchPrices?.[branchId]??product.sellingPrice));if(!Number.isFinite(unitPrice)||unitPrice<0)throw new HttpsError('failed-precondition','Authoritative product price is invalid.');if(requested.clientPrice!==undefined&&money(requested.clientPrice)!==unitPrice&&!member.permissions.includes('sale.price.override'))throw new HttpsError('permission-denied','Price override permission is required.');if(requested.discount>0&&!member.permissions.includes('sale.discount'))throw new HttpsError('permission-denied','Discount permission is required.');const lineSubtotal=money(unitPrice*requested.quantity),discount=money(requested.discount);if(discount>lineSubtotal)throw new HttpsError('invalid-argument','Discount exceeds line subtotal.');const taxRate=Number(product.applicableTaxRate??vendor.taxRate??0),tax=money((lineSubtotal-discount)*taxRate/100),lineTotal=money(lineSubtotal-discount+tax);lines.push({saleId,productId:product.id,sku:String(product.sku||''),productName:String(product.name||''),quantity:requested.quantity,unitPrice,discount,tax,lineSubtotal,lineTotal,currency,taxRate})}
      const subtotal=money(lines.reduce((total,line)=>total+line.lineSubtotal,0)),discountAmount=money(lines.reduce((total,line)=>total+line.discount,0)),taxAmount=money(lines.reduce((total,line)=>total+line.tax,0)),totalAmount=money(lines.reduce((total,line)=>total+line.lineTotal,0));
      const payment=data.payment as Data||{},method=String(payment.method||'').toLowerCase();if(!['cash','card','mobile_money','split'].includes(method))throw new HttpsError('invalid-argument','Payment method is not supported.');if(method==='cash'){const tendered=Number(payment.tenderedAmount);if(!Number.isFinite(tendered)||tendered<totalAmount)throw new HttpsError('failed-precondition','Cash tender is insufficient.');payment.tenderedAmount=money(tendered);payment.changeDue=money(tendered-totalAmount)}else if(String(payment.status).toUpperCase()!=='CONFIRMED'||!String(payment.reference||'').trim())throw new HttpsError('failed-precondition','Electronic payment confirmation evidence is required.');

      const balanceRefs=lines.map(line=>db.doc(`vendors/${vendorId}/inventory_balances/${deterministicInventoryBalanceId({tenantId:vendorId,vendorId,stockLocationId:branchId,productId:line.productId})}`)),legacyRefs=lines.map(line=>db.doc(`vendors/${vendorId}/branch_inventory/${vendorId}_${branchId}_${line.productId}`)),movementRefs=lines.map(line=>db.doc(`vendors/${vendorId}/inventory_movements/${safe(`sale:${saleId}:${line.productId}`)}`)),snapshots=await tx.getAll(...balanceRefs,...legacyRefs,...movementRefs),balances=new Map<string,InventoryBalance>(),legacy=new Map<string,Data>(),movements=new Map<string,InventoryMovement>();
      lines.forEach((line,index)=>{const canonical=snapshots[index].data() as InventoryBalance|undefined,old=snapshots[lines.length+index].data()||{},balance=canonical||{...emptyInventoryBalance({tenantId:vendorId,vendorId,stockLocationId:branchId,productId:line.productId},now),onHandQty:Number(old.quantity||0),version:Number(old.version||0)};balances.set(line.productId,balance);legacy.set(line.productId,old);const movement=snapshots[lines.length*2+index].data() as InventoryMovement|undefined;if(movement)movements.set(movement.idempotencyKey,movement)});
      const context={vendorId,branchId,terminalId,shiftId,cashierId:uid,saleId,commandId,totalAmount,currency},location:StockLocation={id:branchId,tenantId:vendorId,vendorId,type:'BRANCH',name:String(branch.name),code:String(branch.code),status:'ACTIVE',licenceStatus:'LICENSED',createdAt:String(branch.createdAt||now),updatedAt:String(branch.updatedAt||now)},engine=new InventoryPostingEngine(saleRepository(tx,db,context,location,balances,legacy,movements),async identity=>productIds.includes(identity.productId),()=>now),movementIds:string[]=[];
      for(const line of lines){const key=`sale:${saleId}:${line.productId}`,posted=await engine.post({commandId:safe(key),idempotencyKey:key,tenantId:vendorId,vendorId,productId:line.productId,movementType:'SALE',quantity:line.quantity,sourceLocationId:branchId,referenceType:'SALE',referenceId:saleId,actorId:uid,occurredAt:now,correlationId:saleId});movementIds.push(posted.movement.id)}
      if(process.env.FUNCTIONS_EMULATOR==='true'&&data.testFailurePoint==='INVENTORY')throw new HttpsError('aborted','Injected inventory failure.');
      const paymentRecord=clean({id:`payment_${saleId}`,tenantId:vendorId,vendorId,saleId,branchId,terminalId,shiftId,cashierId:uid,method,status:'CONFIRMED',amount:totalAmount,currency,tenderedAmount:payment.tenderedAmount,changeDue:payment.changeDue,provider:payment.provider,reference:payment.reference,confirmedAt:now,createdAt:now});
      if(process.env.FUNCTIONS_EMULATOR==='true'&&data.testFailurePoint==='PAYMENT')throw new HttpsError('aborted','Injected payment failure.');
      const receipt=clean({id:`receipt_${saleId}`,receiptId:`receipt_${saleId}`,receiptNumber:`RCP-${safe(saleId).toUpperCase()}`,tenantId:vendorId,vendorId,saleId,branchId,terminalId,shiftId,cashierId:uid,lines,subtotal,discountAmount,taxAmount,totalAmount,currency,paymentId:paymentRecord.id,issuedAt:now,version:1});
      if(process.env.FUNCTIONS_EMULATOR==='true'&&['RECEIPT','EVENT'].includes(data.testFailurePoint))throw new HttpsError('aborted','Injected receipt or event failure.');
      const order=clean({id:saleId,saleId,orderNumber:`ORD-${safe(saleId).toUpperCase()}`,tenantId:vendorId,vendorId,branchId,branchName:branch.name,terminalId,terminalName:terminal.name,shiftId,cashierId:uid,items:lines.map(line=>({product:{id:line.productId,vendorId,sku:line.sku,name:line.productName,sellingPrice:line.unitPrice,status:'active'},quantity:line.quantity,unitPrice:line.unitPrice,discount:line.discount,subtotal:line.lineTotal})),lines,subtotal,taxAmount,discountAmount,totalAmount,currency,paymentMethod:method,paymentDetails:{cashGiven:paymentRecord.tenderedAmount,changeDue:paymentRecord.changeDue,cardRef:method==='card'?paymentRecord.reference:undefined,mobileProvider:paymentRecord.provider,mobileRef:method==='mobile_money'?paymentRecord.reference:undefined},status:'completed',authoritativeStatus:'COMPLETED',paymentStatus:'CONFIRMED',receiptId:receipt.id,movementIds,checkoutAttemptId:commandId,createdAt:now,completedAt:now,version:1});
      const shiftUpdate={...shift,totalSales:money(Number(shift.totalSales||0)+totalAmount),cashSales:money(Number(shift.cashSales||0)+(method==='cash'?totalAmount:0)),cardSales:money(Number(shift.cardSales||0)+(method==='card'?totalAmount:0)),mobileSales:money(Number(shift.mobileSales||0)+(method==='mobile_money'?totalAmount:0)),transactionCount:Number(shift.transactionCount||0)+1,expectedCash:money(Number(shift.openingCash||0)+Number(shift.cashSales||0)+(method==='cash'?totalAmount:0)),updatedAt:now};
      tx.create(saleRef,order);tx.create(db.doc(`vendors/${vendorId}/payments/${paymentRecord.id}`),paymentRecord);tx.create(db.doc(`vendors/${vendorId}/receipts/${receipt.id}`),receipt);tx.set(db.doc(`vendors/${vendorId}/shifts/${shiftId}`),clean(shiftUpdate));emit(tx,db,context,'SALE_COMPLETION_REQUESTED',now);emit(tx,db,context,'SALE_COMPLETED',now);
      const result={sale:order,order,payment:paymentRecord,receipt,movementIds,shift:shiftUpdate,duplicate:false};tx.create(commandRef,{tenantId:vendorId,vendorId,saleId,commandId,action:'COMPLETE_SALE',actorId:uid,createdAt:now,result:clean({...result,duplicate:true})});return result;
    });
  });
}
